services:
  sharp-readsb-json-parser:
    container_name: sharp-parser
    build:
      context: ./
      dockerfile: Dockerfile
    #image: ghcr.io/ap-andersson/sharp-readsb-json-parser:main
    environment:
      - FeederJsonParser__URL=ultrafeeder
      - FeederJsonParser__Port=30047
      - Logging__LogLevel__FeederJsonParser=Trace
    volumes:
      - ./:/feeder-json-parser/
